name: Publish
on:
    release:
        types: [created]
jobs:
    publish-package:
        runs-on: ubuntu-slim
        steps:
            - uses: actions/checkout@v7
            - uses: actions/setup-node@v7
              with:
                node-version: '22'
            - run: npm install
            - run: npm run docs
            - run: npm pack
            - run: npm publish --access=public
